### PR TITLE
Don't abort the entire RGO run on failed prep (just log it)

### PR DESCRIPTION
**Pull request by kontura**
Failed prep means broken SRPM which will later fail during a build
anyway but all the other working SRPMs can succeed.

### CODE REVIEW

**Comment by lukash** [comment]
What happens after the prep fails? I would assume submitting the copr job will fail because of a missing srpm? Does this ultimately do what we want?

**Comment by kontura** [comment]
The srpm is actually not missing its just broken, even this function `try_prep` takes it as a param.
So after the prep fails it submits the Copr jobs fine but the broken srpm fails to build (because it fails the prep step).

I have tried it in my Copr: https://copr.fedorainfracloud.org/coprs/amatej/dnf-nightly/builds/ and if you look at the failing libsolv build there is:
```
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
1 out of 1 hunk ignored -- saving rejects to file bindings/solv.i.rej
error: Bad exit status from /var/tmp/rpm-tmp.5Gpetx (%prep)
```

**Comment by lukash** [comment]
Right, the patches are applied in Copr when the build from srpm happens. So what's the purpose of the `try_prep()` anyway? It would seem it was to try to apply the patches so that the build isn't submitted to Copr if they don't apply?

Now you reduce it to try to apply patches, log the result and then proceed in any case...

So to preserve the logic we should drop the srpm from the builds if it fails the `try_prep()`? Alternatively we could drop the `try_prep()` step instead, I don't like it too much anyway... The prep is being done on the rgo host system, which in theory could have a different version of something like rpm and behave differently... Granted the srpm is also being built on that system, but at least that's not being done twice with a potential for a discrepancy.

**Comment by kontura** [comment]
I would also be in favor of dropping it, although rgo has a mode where it just makes the srpms (no rpmbuild or Copr build), maybe we could move the prep step into the srpm mode only?

**Comment by lukash** [comment]
Yeah, sounds good.

**Pull request merged**
